name: jack_toolkits
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=1.3.0
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bokeh=2.2.3
  - ca-certificates=2020.10.14
  - cachey=0.2.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.3
  - contextvars=2.4
  - cryptography=2.8
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - distributed=2.30.0
  - freetype=2.10.4
  - fsspec=0.8.3
  - heapdict=1.0.1
  - icc_rt=2019.0.0
  - idna=2.8
  - immutables=0.14
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - kafka-python=2.0.2
  - libpng=1.6.37
  - libtiff=4.1.0
  - line_profiler=2.1.2
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - msgpack-python=1.0.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.3
  - pandas=1.0.3
  - parso=0.8.0
  - partd=1.1.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.0.2
  - pluggy=0.13.1
  - prettytable=0.7.2
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - py=1.8.1
  - pycparser=2.19
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=5.4.3
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.3.1
  - requests=2.22.0
  - retrying=1.3.3
  - setuptools=45.2.0
  - six=1.14.0
  - sortedcontainers=2.2.2
  - sqlite=3.31.1
  - tblib=1.7.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.9
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.1.7
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.4
