name: PythonToolkit
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - idna=2.10
  - openssl=1.1.1k
  - pip=21.0.1
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.7.10
  - requests=2.25.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
